#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 Team Twist My ARM
#

#
# XXX Stub
#

$(OBJS_DIR)/%.o:	$(UTSBASE)/armv7/qvirt/aboot/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSBASE)/armv7/qvirt/aboot/%.s
	$(COMPILE.s) -o $@ $<

INC_PATH += -I$(UTSBASE)/$(PLATFORM)
